[project]
name = "api"
version = "0.1.0"
description = "FastAPI application for highlight API"
requires-python = ">=3.13"
dependencies = [
    "shared",
    "fastapi[all]>=0.115.0",
    "uvicorn[standard]>=0.32.0",
    "python-multipart>=0.0.18",
    "celery>=5.4.0",  # For queueing tasks
]

[tool.uv.sources]
shared = { workspace = true }

[project.optional-dependencies]
test = [
    "pytest>=8.3.0",
    "pytest-asyncio>=0.25.0",
    "httpx>=0.27.0",
    "testcontainers[postgres]>=4.0.0",
    "factory-boy>=3.3.0",
    "faker>=33.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"