name: Code Quality

on:
  push:
    branches: [ main, complete-rewrite ]
  pull_request:
    branches: [ main, complete-rewrite ]

jobs:
  quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"
    
    - name: Install dependencies
      run: |
        uv pip install -e ".[dev]"
    
    - name: Check for security vulnerabilities
      run: |
        uv run bandit -r src/ -f json -o bandit-report.json || true
        uv run bandit -r src/ -ll
      continue-on-error: true
    
    - name: Check dependency vulnerabilities
      run: |
        uv run safety check --json --output safety-report.json || true
        uv run safety check
      continue-on-error: true
    
    - name: Run complexity analysis
      run: |
        uv run radon cc src/ --min=B
      continue-on-error: true
    
    - name: Check code duplication
      run: |
        uv run radon raw src/
      continue-on-error: true
    
    - name: Upload reports as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: quality-reports
        path: |
          bandit-report.json
          safety-report.json
      continue-on-error: true